- name: Create mongod/files directory
  file:
    path: "{{ playbook_dir }}/roles/mongod/files"
    state: directory
    mode: 0775
  run_once: True
  delegate_to: localhost

- name: Prepare authorization key file
  local_action: shell openssl rand -base64 756 > {{ playbook_dir }}/roles/mongod/files/secret
  run_once: True

- name: Login to vault
  local_action: |
    shell curl --fail -s \
                --request POST \
                --data '{"role_id":"{{ vaultRoleId }}", "secret_id":"{{ vaultSecretId }}"}' \
                {{ vault_addr }}/v1/auth/approle/login > {{ playbook_dir }}/mongotoken.raw \
        && jq -r '.auth.client_token' {{ playbook_dir }}/mongotoken.raw > {{ playbook_dir }}/mongotoken \
        && rm {{ playbook_dir }}/mongotoken.raw
  run_once: True
