---

- hosts: mongo_servers
  vars_prompt:
    - name: "vaultRoleId"
      prompt: "Vault Role ID for Ansible"
    - name: "vaultSecretID"
      prompt: "Vault Secret for Ansible"
  roles:
  - role: prep
  - role: common
  - role: mongod
